# Generated by Django 3.2.4 on 2021-06-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalprofile',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='generalprofile',
            name='address_2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Datos adicionales'),
        ),
    ]
